local pauselayer=class("pauseLayer",function ()
	return cc.Layer:create()
end)

function pauselayer.create(texture)
    local scene=cc.Scene:create()
	local pause=pauselayer.new()
	pause:init(texture)
	scene:addChild(pause)
	return scene
end

function pauselayer:init(texture)
	local backsprite=cc.Sprite:createWithTexture(texture:getSprite():getTexture())
	local vsize=cc.Director:getInstance():getVisibleSize()
	backsprite:setPosition(vsize.width/2,vsize.height/2)
	backsprite:setOpacity(50)
	backsprite:setFlippedY(true)
	self:addChild(backsprite)
	local menuback=cc.Sprite:create("back_pause.png")
	menuback:setPosition(vsize.width/2,vsize.height/2)
	self:addChild(menuback)
    local continue_button=cc.MenuItemImage:create("pausecontinue.png","pausecontinue.png","pausecontinue.png")
    continue_button:registerScriptTapHandler(function()
        cc.Director:getInstance():popScene()
    end)
    continue_button:setPosition(vsize.width/2 ,vsize.height/2+30)
    local restart_button=cc.MenuItemImage:create("pause_restart.png","pause_restart.png","pause_restart.png")
    restart_button:registerScriptTapHandler(function()
        cc.Director:getInstance():popScene()
        cc.Director:getInstance():replaceScene(require("HelloGame").create())
    end)
    restart_button:setPosition(vsize.width/2,vsize.height/2-20)
    local gamelogin_button=cc.MenuItemImage:create("pause_login.png","pause_login.png","pause_login.png")
    gamelogin_button:registerScriptTapHandler(function()
        --cc.Director:getInstance():popScene()
       -- cc.Director:getInstance():replaceScene(require("start").create())
    end)
    gamelogin_button:setPosition(vsize.width/2,vsize.height/2-70)
    local menu=cc.Menu:create(continue_button,restart_button,gamelogin_button)
    self:addChild(menu)
    menu:setPosition(0,0)
end
return pauselayer